name: danwoodward
favicon: null
layout_spectrum: 0.45932444580830634
typography_spectrum: 0.42256407672539353
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5970232654362917
  lightness: 0.3798804604448378
  saturation: 0.48627824895083904
  rhythmicContrast: 0.6644556592218578
purpose: []
